# Generated by Django 4.2.7 on 2024-01-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='number',
        ),
        migrations.AddField(
            model_name='week',
            name='week_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
