# Generated by Django 4.2.7 on 2024-01-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system_app', '0003_alter_week_week_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='week_number',
            field=models.IntegerField(),
        ),
    ]
