# Generated by Django 4.2.7 on 2024-01-28 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('week_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='died',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='week_app.died'),
        ),
    ]
