# Generated by Django 4.2.7 on 2024-01-26 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('week_app', '0002_died_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='died',
            name='modify_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
