# Generated by Django 4.2.7 on 2024-01-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_app', '0002_alter_comment_died'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
    ]
