# Generated by Django 4.2.7 on 2024-01-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week_app', '0003_week'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Week',
        ),
    ]
