# Generated by Django 4.2.7 on 2024-01-29 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system_app', '0002_remove_week_number_week_week_number'),
        ('week_app', '0006_remove_died_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='died',
            name='edit',
        ),
        migrations.AddField(
            model_name='died',
            name='week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_system_app.week'),
            preserve_default=False,
        ),
    ]
