# Generated by Django 4.2.7 on 2024-01-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week_app', '0007_remove_died_edit_died_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='died',
            name='week',
        ),
    ]
