# Generated by Django 4.2.7 on 2024-01-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week_app', '0008_remove_died_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
    ]
