# Generated by Django 4.2.7 on 2024-01-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_app', '0010_rename_created_date_comment_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='died',
            name='week',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
