# Generated by Django 4.2.7 on 2024-01-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week_app', '0011_died_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='died',
            old_name='week',
            new_name='week_number',
        ),
    ]
