# Generated by Django 4.2.7 on 2024-01-30 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system_app', '0003_alter_week_week_number'),
        ('week_app', '0014_remove_died_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='died',
            name='week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='died_id', to='auth_system_app.week'),
            preserve_default=False,
        ),
    ]
