# Generated by Django 4.2.7 on 2024-01-30 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week_app', '0015_died_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='died',
            name='week',
        ),
    ]
