# Generated by Django 4.2.7 on 2024-01-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_app', '0016_remove_died_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='died',
            name='week_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
