# Generated by Django 4.2.7 on 2024-01-30 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week_app', '0022_alter_died_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='died',
            name='image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
