# Generated by Django 4.2.7 on 2024-01-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_app', '0023_remove_died_image_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='died',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='died_images/'),
        ),
    ]
