# Generated by Django 4.2.7 on 2024-01-30 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('week_app', '0024_died_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='died_images/')),
                ('died', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='week_app.died')),
            ],
        ),
    ]
