# Generated by Django 4.2.7 on 2024-01-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_app', '0028_remove_died_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='died',
            name='image',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
