# Generated by Django 4.2.7 on 2024-01-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_app', '0029_died_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='died',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='died_images/'),
        ),
    ]
