# Generated by Django 4.2.7 on 2024-01-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_app', '0030_alter_died_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='died',
            name='week_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
