# Generated by Django 4.2.7 on 2024-01-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_app', '0031_alter_died_week_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='week_app/static/died_images/'),
        ),
    ]
