# Generated by Django 4.2.7 on 2024-01-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week_app', '0032_image_image_id_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_id',
        ),
    ]
