# Generated by Django 4.2.7 on 2024-01-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_app', '0033_remove_image_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='died',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='week_app/static/died_images/'),
        ),
    ]
