# Generated by Django 4.2.7 on 2024-01-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_app', '0035_alter_died_week_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='died',
            name='week_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
